# Generated by Django 5.1.2 on 2024-10-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('time_of_completion', models.IntegerField(choices=[(1, '1 month'), (2, '2 months'), (3, '3 months'), (4, '4 months'), (5, '5 months'), (6, '6 months')])),
                ('require_hosting', models.BooleanField(default=False)),
                ('project_use', models.CharField(choices=[('personal', 'Personal Use'), ('business', 'Business Use'), ('enterprise', 'Enterprise Use'), ('non-profit', 'Non-Profit Use')], max_length=20)),
                ('require_it_maintenance', models.BooleanField(default=False)),
            ],
        ),
    ]
