# Generated by Django 5.1.2 on 2024-10-15 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='name',
            new_name='project_name',
        ),
    ]
